### ISSUE TITLE
Can't instantiate abstract class with abstract methods

### ISSUE THREAD

**Issue by sdwfrost** [st--/vbpp#4]
Using Python 3.8.2 on Ubuntu 20.04, running the demo gives me:

```
Traceback (most recent call last):
  File "demo_coal_1d.py", line 63, in <module>
    demo()
  File "demo_coal_1d.py", line 43, in demo
    model = build_model(events, domain)
  File "demo_coal_1d.py", line 37, in build_model
    model = VBPP(feature, kernel, domain, q_mu, q_S, beta0=beta0, num_events=num_events)
TypeError: Can't instantiate abstract class VBPP with abstract methods maximum_log_likelihood_objective
```

**Comment by st--** [comment]
Hi @sdwfrost, thanks for bringing this to my attention! I've now fixed this issue (and a couple others that prevented compatibility with the GPflow 2 release) in #5. Please let me know if you encounter any other issues :) (And if you'd be willing to tell me, I'd be super curious what you're doing with this code!)

**Comment by sdwfrost** [comment]
Thanks! Works great now. I have a few applications in mind. One of them is to do large-scale inference of changes in effective population size from phylogenetic data (see e.g. [Palacios and Minin 2013](https://onlinelibrary.wiley.com/doi/abs/10.1111/biom.12003).

**Comment by st--** [comment]
Ah cool, I'd be happy to chat some more if you'd like - would love to have more of my code actually used by others (and happy to help in the process). The premonition project linked on your account looks really interesting too! You could join us on the GPflow slack ([invite link](https://join.slack.com/t/gpflow/shared_invite/enQtOTE5MDA0Nzg5NjA2LTYwZWI3MzhjYjNlZWI1MWExYzZjMGNhOWIwZWMzMGY0YjVkYzAyYjQ4NjgzNDUyZTgyNzcwYjAyY2QzMWRmYjE)), my account there is `stj`.

**Comment by st--** [comment]
(In a couple of other Cox process papers I've seen, the authors seem to not fit properly the VBPP model that they compare against. In any case there's probably a couple of things I'd do differently now.)
